###
POST http://localhost:3333/feedbacks
content-type: application/json

{
    "type": "Marcado pago",
    "comment": "Mercado pago solicitado",
    "screenshot": ""
}

###
POST http://localhost:3333/subscribes
content-type: application/json

{
    "status": 1,
    "subjet": "Anderson Lopes",
    "email": "teste@teste.com",
    "message": "Teste de mensagem",
    "newsletter": false
}
###
POST http://localhost:3333/etiquetas
content-type: application/json

{
    "nome": "THAYS EMILLY SILVA",
    "endereco": "AV DAS ARAUCARIAS, 4150",
    "complemento": "BLOCO B APTO 508",
    "observacoes": "RESIDENCIAL BLEND",
    "telefone": "(11) 989897158",
    "bairro": "SUL (AGUAS CLARAS)",
    "cidade": "BRASILIA",
    "estado": "DF",
    "cep": "71936250",
    "aeroporto": "BSB",
    "nota": "1483",
    "peso": "0,394",
    "minuta": "66061936970",
    "pedido": "1483"
}

###
GET http://localhost:3333/etiquetas/1350